const keyframes = require('./keyframes')
const keyframesLightSpeed = require('./lightspeed')
const keyframesFlip = require('./flip')
const keyframesRotateIn = require('./rotateIn')
const keyframesRotateOut = require('./rotateOut')
const keyframesRoll = require('./roll')
const keyframesZoomIn = require('./zoomIn')
const keyframesZoomOut = require('./zoomOut')
const keyframesBounceIn = require('./bounceIn')
const keyframesBounceOut = require('./bounceOut')
const keyframesSlideIn = require('./slideIn')
const keyframesSlideOut = require('./slideOut')
const keyframesFadeIn = require('./fadeIn')
const keyframesFadeOut = require('./fadeOut')
const keyframesBackIn = require('./backIn')
const keyframesBackOut = require('./backOut')

export const availableKeyframes = {
  '@keyframes bounce': keyframes.keyframeBounce,
  '@keyframes flash': keyframes.keyframeFlash,
  '@keyframes pulse': keyframes.keyframePulse,
  '@keyframes rubberBand': keyframes.keyframeRubberBand,
  '@keyframes shakeX': keyframes.keyframeShakeX,
  '@keyframes shakeY': keyframes.keyframeShakeY,
  '@keyframes headShake': keyframes.keyframeHeadShake,
  '@keyframes swing': keyframes.keyframeSwing,
  '@keyframes tada': keyframes.keyframeTada,
  '@keyframes wobble': keyframes.keyframeWobble,
  '@keyframes jello': keyframes.keyframeJello,
  '@keyframes heartBeat': keyframes.keyframeHeartBeat,
  '@keyframes hinge': keyframes.keyframeHinge,
  '@keyframes jackInTheBox': keyframes.keyframeJackInTheBox,
  '@keyframes lightSpeedInLeft': keyframesLightSpeed.keyframeLightSpeedInLeft,
  '@keyframes lightSpeedInRight': keyframesLightSpeed.keyframeLightSpeedInRight,
  '@keyframes lightSpeedOutLeft': keyframesLightSpeed.keyframeLightSpeedOutLeft,
  '@keyframes lightSpeedOutRight': keyframesLightSpeed.keyframeLightSpeedOutRight,
  '@keyframes flip': keyframesFlip.keyframeFlip,
  '@keyframes flipInX': keyframesFlip.keyframeFlipInX,
  '@keyframes flipInY': keyframesFlip.keyframeFlipInY,
  '@keyframes flipOutX': keyframesFlip.keyframeFlipOutX,
  '@keyframes flipOutY': keyframesFlip.keyframeFlipOutY,
  '@keyframes rotateIn': keyframesRotateIn.keyframeRotateIn,
  '@keyframes rotateInDownLeft': keyframesRotateIn.keyframeRotateInDownLeft,
  '@keyframes rotateInDownRight': keyframesRotateIn.keyframeRotateInDownRight,
  '@keyframes rotateInUpLeft': keyframesRotateIn.keyframeRotateInUpLeft,
  '@keyframes rotateInUpRight': keyframesRotateIn.keyframeRotateInUpRight,
  '@keyframes rotateOut': keyframesRotateOut.keyframeRotateOut,
  '@keyframes rotateOutDownLeft': keyframesRotateOut.keyframeRotateOutDownLeft,
  '@keyframes rotateOutDownRight': keyframesRotateOut.keyframeRotateOutDownRight,
  '@keyframes rotateOutUpLeft': keyframesRotateOut.keyframeRotateOutUpLeft,
  '@keyframes rotateOutUpRight': keyframesRotateOut.keyframeRotateOutUpRight,
  '@keyframes rollIn': keyframesRoll.keyframeRollIn,
  '@keyframes rollOut': keyframesRoll.keyframeRollOut,
  '@keyframes zoomIn': keyframesZoomIn.keyframeZoomIn,
  '@keyframes zoomInDown': keyframesZoomIn.keyframeZoomInDown,
  '@keyframes zoomInLeft': keyframesZoomIn.keyframeZoomInLeft,
  '@keyframes zoomInRight': keyframesZoomIn.keyframeZoomInRight,
  '@keyframes zoomInUp': keyframesZoomIn.keyframeZoomInUp,
  '@keyframes bounceIn': keyframesBounceIn.keyframeBounceIn,
  '@keyframes bounceInDown': keyframesBounceIn.keyframeBounceInDown,
  '@keyframes bounceInLeft': keyframesBounceIn.keyframeBounceInLeft,
  '@keyframes bounceInRight': keyframesBounceIn.keyframeBounceInRight,
  '@keyframes bounceInUp': keyframesBounceIn.keyframeBounceInUp,
  '@keyframes bounceOut': keyframesBounceOut.keyframeBounceOut,
  '@keyframes bounceOutDown': keyframesBounceOut.keyframeBounceOutDown,
  '@keyframes bounceOutLeft': keyframesBounceOut.keyframeBounceOutLeft,
  '@keyframes bounceOutRight': keyframesBounceOut.keyframeBounceOutRight,
  '@keyframes bounceOutUp': keyframesBounceOut.keyframeBounceOutUp,
  '@keyframes zoomOut': keyframesZoomOut.keyframeZoomOut,
  '@keyframes zoomOutDown': keyframesZoomOut.keyframeZoomOutDown,
  '@keyframes zoomOutLeft': keyframesZoomOut.keyframeZoomOutLeft,
  '@keyframes zoomOutRight': keyframesZoomOut.keyframeZoomOutRight,
  '@keyframes zoomOutUp': keyframesZoomOut.keyframeZoomOutUp,
  '@keyframes slideInDown': keyframesSlideIn.keyframeSlideInDown,
  '@keyframes slideInLeft': keyframesSlideIn.keyframeSlideInLeft,
  '@keyframes slideInRight': keyframesSlideIn.keyframeSlideInRight,
  '@keyframes slideInUp': keyframesSlideIn.keyframeSlideInUp,
  '@keyframes slideOutDown': keyframesSlideOut.keyframeSlideOutDown,
  '@keyframes slideOutLeft': keyframesSlideOut.keyframeSlideOutLeft,
  '@keyframes slideOutRight': keyframesSlideOut.keyframeSlideOutRight,
  '@keyframes slideOutUp': keyframesSlideOut.keyframeSlideOutUp,
  '@keyframes fadeIn': keyframesFadeIn.keyframeFadeIn,
  '@keyframes fadeInDown': keyframesFadeIn.keyframeFadeInDown,
  '@keyframes fadeInDownBig': keyframesFadeIn.keyframeFadeInDownBig,
  '@keyframes fadeInLeft': keyframesFadeIn.keyframeFadeInLeft,
  '@keyframes fadeInLeftBig': keyframesFadeIn.keyframeFadeInLeftBig,
  '@keyframes fadeInRight': keyframesFadeIn.keyframeFadeInRight,
  '@keyframes fadeInRightBig': keyframesFadeIn.keyframeFadeInRightBig,
  '@keyframes fadeInTopLeft': keyframesFadeIn.keyframeFadeInTopLeft,
  '@keyframes fadeInTopRight': keyframesFadeIn.keyframeFadeInTopRight,
  '@keyframes fadeInBottomLeft': keyframesFadeIn.keyframeFadeInBottomLeft,
  '@keyframes fadeInBottomRight': keyframesFadeIn.keyframeFadeInBottomRight,
  '@keyframes fadeInUp': keyframesFadeIn.keyframeFadeInUp,
  '@keyframes fadeInUpBig': keyframesFadeIn.keyframeFadeInUpBig,
  '@keyframes fadeOut': keyframesFadeOut.keyframeFadeOut,
  '@keyframes fadeOutDown': keyframesFadeOut.keyframeFadeOutDown,
  '@keyframes fadeOutDownBig': keyframesFadeOut.keyframeFadeOutDownBig,
  '@keyframes fadeOutLeft': keyframesFadeOut.keyframeFadeOutLeft,
  '@keyframes fadeOutLeftBig': keyframesFadeOut.keyframeFadeOutLeftBig,
  '@keyframes fadeOutRight': keyframesFadeOut.keyframeFadeOutRight,
  '@keyframes fadeOutRightBig': keyframesFadeOut.keyframeFadeOutRightBig,
  '@keyframes fadeOutUp': keyframesFadeOut.keyframeFadeOutUp,
  '@keyframes fadeOutUpBig': keyframesFadeOut.keyframeFadeOutUpBig,
  '@keyframes fadeOutTopLeft': keyframesFadeOut.keyframeFadeOutTopLeft,
  '@keyframes fadeOutTopRight': keyframesFadeOut.keyframeFadeOutTopRight,
  '@keyframes fadeOutBottomLeft': keyframesFadeOut.keyframeFadeOutBottomLeft,
  '@keyframes fadeOutBottomRight': keyframesFadeOut.keyframeFadeOutBottomRight,
  '@keyframes backInDown': keyframesBackIn.keyframeBackInDown,
  '@keyframes backInUp': keyframesBackIn.keyframeBackInUp,
  '@keyframes backInLeft': keyframesBackIn.keyframeBackInLeft,
  '@keyframes backInRight': keyframesBackIn.keyframeBackInRight,
  '@keyframes backOutDown': keyframesBackOut.keyframeBackOutDown,
  '@keyframes backOutUp': keyframesBackOut.keyframeBackOutUp,
  '@keyframes backOutLeft': keyframesBackOut.keyframeBackOutLeft,
  '@keyframes backOutRight': keyframesBackOut.keyframeBackOutRight,
}
